### ISSUE TITLE
Loading int_heat_capacity

### ISSUE THREAD

**Issue by ivKberg** [dschick/udkm1Dsim#105] opened 2022-04-13 09:50 UTC
Sometimes the sympy integration of the specific heat fails in the initialization of the layers. This is already mentioned in the code in 'layers.py' and is printed as an error message. In my case this did not happen, or, maybe, I did not wait long enough for the error to pop. In any case, the suggested fix :" [...] You can set the analytical anti-derivative of the heat capacity of your layer as function str of the temperature T by typing layer.int_heat_capacity = \'c(T)\' [..]" seems to not work (at least for me). 
A fix that worked on my machine (I believe) was to use the existing int_heat_capacity property as a setter with a check_input() line, making a new int_heat_capacity property which simply returns the value, and adding a line in the __init__ to call the setter. I also commented the recalculation in the heat_capacity.

 But maybe I am overlooking something? There is surely an easier way to change this in just in a line or two.  Furthermore, the program does now not calculate the values, for example, if none are given. 

My changes in layers.py basically are:

line 113 
`self.int_heat_capacity = kwargs.get('int_heat_capacity', 0)`

line 421
```
    @int_heat_capacity.setter
    def int_heat_capacity(self, int_heat_capacity):
        self._int_heat_capacity, self.int_heat_capacity_str = self.check_input(int_heat_capacity) #here
        if hasattr(self, '_int_heat_capacity') and isinstance(self._int_heat_capacity, list):
            return self._int_heat_capacity
        else:
              ....
```
line 445
```
    @property
    def int_heat_capacity(self):
        return self._int_heat_capacity
```
PS: I guess this is also true for lin_therm_exp, but I haven't checked.

**Comment by dschick** [comment] 2022-04-13 20:31
Hi @ivKberg ,

Thanks for your issue. Could you please also share a piece of code, which is triggering your issue?

**Comment by ivKberg** [comment] 2022-04-14 07:36
Hi, sure! Maybe I should also add the initial issue that led me here to clarify. When trying to use a sum of a gaussian and a sigmoidal function for the heat capacity of Co the sympy integration did not work and the program got stuck in the initialization of the layers. The line I used is:
```
prop_Co['heat_capacity'] =['0.6*T+365*exp(-(T-1387) ** 2/192 ** 2)-(1+exp(-(T-1395))) ** (-1) * 468+20', 693*u.J/u.kg/u.K, 1/Codens]
```
employing the m3TM. The first term, here the electronic heat capacity triggered the issue. As mentioned in the first post, I tried to circumvent the issue by giving the analytical function of the integral (got it from Wolframalpha, I am lazy)  as
```
prop_Co['int_heat_capacity'] = ['0.3*T**2-323.5 * erf((1387-T)/192)-468 * ln(exp(1395)+exp(T))+20*T', '693*T', 'ln(8860)']
```
. Nevertheless, the issue remained. I also tried adding the property in `ud.Unitcell(int_heat_capacity = ..)` or later in my layer as `Colayer.int_heat_capacity = .. ` without any luck.

The search as to why the `int_heat_capacity` is still being calculated instead of the program using the provided function led me to the above-mentioned situation.

Hopefully, this makes some sense. I also realized that maybe something is wrong with how I circumvented things. It appears to make no difference what function I give the 'int_heat_capacity_ property. However, I checked that it has the right form/values by printing the string representation. Is the int_heat_capacity always needed? Maybe I also add the excitation I use:
```
h = ud.Heat(S, True)
...
h.excitation = {'fluence': [40]*u.mJ/u.cm**2,
                'delay_pump':  [0]*u.fs,
                'pulse_width':  [60]*u.fs,
                'multilayer_absorption': True,
                'wavelength': 800*u.nm,
                'theta': 7*u.deg}
...
temp_map, delta_temp = h.get_temp_map(delays, init_temp)
```
Edit: Formatted the equation with spaces to display it correctly.

**Comment by dschick** [comment] 2022-04-19 07:28
Hi @ivKberg ,

thanks for the detailed example. It seems that `sympy` is not able to carry out the analytical integration of our `heat_capacity` function.
So the first idea is of course to simply that.

Secondly, you could avoid calling the automatic integration of the `heat_capacity` property by setting its `private` equivalent by doing: 
```
prop_Co._heat_capacity = [.., ..., ...]
```
But please be aware, that instead of strings you have to provide `lambda` functions here instead. Please check the logic in [`check_input`](https://github.com/dschick/udkm1Dsim/blob/38832881f1a71317131295624dc8dd7269a139a8/udkm1Dsim/structures/layers.py#L148-L211) method of the `layer` class.

Afterward you should be able to set the `int_heat_capacity` as you described above.

Best

Daniel

**Comment by ivKberg** [comment] 2022-04-20 11:03
Hi @dschick,

Thank you for the reply and the suggestions so far!
A simpler form of the heat capacity, i.e., a polynomial form, was actually my first approach. However, since they love to diverge once the temperature goes only slightly above (or below) the approximated range, I decided against using one. Also, it was super annoying to use 12-14 coefficients :/. 

Anyways, I tried setting the private property but I am still stuck in the intergration. Can you provide a quick example on setting the lambda functions? I am not used to them and I am not sure if it is correct what I am doing.

So far I tried using:
```
prop_Co['heat_capacity'] = [ ... , ... , ...]

prop_Co['_heat_capacity'] = [lambda T: 0.6*T+365 * np.exp(-(T-1387) **2/192 **2)-(1+np.exp(-(T-1395))) **(-1) *468+20,lambda T: 693*T,lambda T: (1/8860)*T]
```
which still gets stuck in the integration.

Afterwards, I tried:
```
prop_Co['heat_capacity'] = [ ... , ... , ...]

prop_Co._heat_capacity = [lambda T: 0.6*T+365*np.exp(-(T-1387) **2/192 **2)-(1+np.exp(-(T-1395))) **(-1)*468+20,lambda T: 693*T,lambda T: (1/8860)*T]
```
which results in an error: " 'dict' object has no attribute '_heat_capacity' ". 

I also tried setting it in UnitCell:
```
Colayer = ud.UnitCell('Co', 'Cobalt layer', c_Co, **prop_Co, density = Codens, _heat_capacity = [... , ... , ...])
```
which remains stuck in the integration. And if I don't set the public property, or do it later, I get an error that the system size of the heat properties does not match.

Happy about any feedback, and thanks again for the suggestions given already

**Comment by dschick** [comment] 2022-04-20 11:20
Hi,

sorry, I could have provided an example already. Maybe you can use the code formatting function of  Markdown, to make your post better readable (I have reformatted your post myself till now)

There is actually just one missing option :)

The actual dictionary `prop_Co` does not know about public or private attributes. This `dict` is just a helper on initalization of the `UnitCell` object.
Also on initialization you cannot access private attributes by design of the `__init__()` method of the class.

So the trick is simply to DO NOT define the `heat_capacity` on initialization:
```
Colayer = ud.UnitCell('Co', 'Cobalt layer', c_Co, **prop_Co, density = Codens)
```
which results in an empty `heat_capacity` property.
Then afterwards you can set the private attribute simply by:
```
Colayer._heat_capacity = [lambda T: 0.6*T+365*np.exp(-(T-1387) **2/192 **2)-(1+np.exp(-(T-1395))) **(-1)*468+20,lambda T: 693*T,lambda T: (1/8860)*T]
```
and as written above the `int_heat_capacity` should then work the normal way by:
```
Colayer.int_heat_capacity = ['0.3*T**2-323.5 * erf((1387-T)/192)-468 * ln(exp(1395)+exp(T))+20*T', '693*T', 'ln(8860)']
```

Please note, that by setting the attribute the *normal*  way, the mathematical functions like `erf` and `log` are already correctly `lambdified` with the according `numpy` prefixes.

Btw: I think you need to use `log` instead of `ln`

**Comment by ivKberg** [comment] 2022-04-20 14:08
Hi @dschick,

thank you for the clarification! However, if I do not set a heat_capacity, for example :

`prop_Co['therm_cond'] = [78*u.W/(u.m *u.K), 12*u.W/(u.m *u.K), 0]`
`prop_Co['lin_therm_exp'] = [0, 12e-6,0]`
`prop_Co['sub_system_coupling'] = [['1.2e18*(T_1-T_0)','1.2e18*(T_0-T_1)','1.2e18*T_2*T_1/1388*(1-T_2* (1 + 2/(exp(2*T_2*1388/T_0) - 1) ))']`

`Colayer = ud.UnitCell('Co', 'Cobalt layer', c_Co, **prop_Co, density = Codens, num_sub_systems = 3)`
`Colayer._heat_capacity = [lambda T: 0.9*T**2, lambda T: 700*T, lambda T: 1/8000*T]`

I always get the error of different sub system sizes: 

`ValueError: Heat capacity, thermal conductivity, linear thermal expansion and subsystem coupling have not the same number of elements!`

I assume this happens since I am setting the heat conduction, lin. therm. expansion, and sub system coupling already. All three are 3d but the default heat capacity is 1d (?).  It works when setting all thermal Colayer attributes like: 

`Colayer = ud.UnitCell('Co', 'Cobalt layer', c_Co, **prop_Co, density = Codens, num_sub_systems = 3)`
`Colayer._heat_capacity = [lambda T: 0.9*T**2,lambda T: 0.9*T**2,lambda T: 0.9*T**2]`
`Colayer._therm_cond = [78*u.W/(u.m *u.K), 12*u.W/(u.m *u.K), 0]`
`Colayer._lin_therm_exp = [0, 12e-6,0]`
`Colayer._sub_system_coupling = [lambda T: 1*T**2,lambda T: 2*T**2,lambda T: 3*T**2]`

Unfortunately, now I do not know how to define the sub_system_coupling in the right fashion. Furthermore, this comes at the cost of the nice string syntax for defining the attributes. Is there a good way to deal with the issue, or am I missing something?

**Comment by dschick** [comment] 2022-04-20 19:08
okay, you found a little bug, because indeed you have to set the `heat_capacity` as well.
I suggest to initially set some generic values like
```
prop_Co['heat_capacity'] = [1, 1, 1]
```
in addition to the other 3TM parameters.
Then in a second step you can continue with
```
Colayer._heat_capacity = [lambda T: 0.9*T**2, lambda T: 700*T, lambda T: 1/8000*T]
```
And also setting the 
```
Colayer.int_heat_capacity = ['0.3*T**2-323.5 * erf((1387-T)/192)-468 * ln(exp(1395)+exp(T))+20*T', '693*T', 'ln(8860)']
```

Plesae also check the examples on the different ways how `UnitCell` and `AmorphousLayer` objects are initialized as you can add multiple `Atom`s to a `UnitCell` at different `c-axis` positions.

**Comment by ivKberg** [comment] 2022-04-25 08:01
Hi @dschick,

OK, I believe now everything runs nicely. Thank you for the feedback!

**Comment by dschick** [comment] 2022-04-25 08:06
you are welcome - closing

**Closed as completed by dschick** 2022-04-25 08:06 UTC
Labels: good first issue
